import { prisma } from '@/lib/database/client';
import type { RuleTrigger, TaskPriority, LifecycleStage } from '@prisma/client';
import { createTask } from '@/lib/crm/task';
import { createTicket } from '@/lib/crm/ticket';
import { createDeal } from '@/lib/crm/deal';

export interface RuleCondition {
  field: string;
  operator: 'equals' | 'not_equals' | 'contains' | 'gte' | 'lte' | 'exists';
  value: unknown;
}

export interface RuleAction {
  type: 'CREATE_TASK' | 'CREATE_TICKET' | 'CREATE_DEAL' | 'ADD_TAG' | 'UPDATE_LIFECYCLE';
  params: Record<string, unknown>;
}

export interface EvaluateRulesInput {
  workspaceId: string;
  trigger: RuleTrigger;
  entityId?: string;
  contactId?: string;
  companyId?: string;
  data: Record<string, unknown>;
}

/**
 * Idempotent, loop-protected workspace rules engine.
 */
export async function evaluateAutomationRules(input: EvaluateRulesInput): Promise<number> {
  const { workspaceId, trigger, contactId, companyId, data } = input;

  const rules = await prisma.automationRule.findMany({
    where: {
      workspaceId,
      trigger,
      active: true,
    },
  });

  let executedCount = 0;

  for (const rule of rules) {
    const conditions = rule.conditions as unknown as RuleCondition[];
    const actions = rule.actions as unknown as RuleAction[];

    const matches = conditions.every((cond) => evaluateCondition(cond, data));
    if (!matches) continue;

    for (const action of actions) {
      await executeAction(workspaceId, action, { contactId, companyId, ...data });
      executedCount++;
    }
  }

  return executedCount;
}

function evaluateCondition(cond: RuleCondition, data: Record<string, unknown>): boolean {
  const val = data[cond.field];
  if (cond.operator === 'exists') return val !== undefined && val !== null;
  if (val === undefined || val === null) return false;

  switch (cond.operator) {
    case 'equals':
      return String(val).toLowerCase() === String(cond.value).toLowerCase();
    case 'not_equals':
      return String(val).toLowerCase() !== String(cond.value).toLowerCase();
    case 'contains':
      return String(val).toLowerCase().includes(String(cond.value).toLowerCase());
    case 'gte':
      return Number(val) >= Number(cond.value);
    case 'lte':
      return Number(val) <= Number(cond.value);
    default:
      return false;
  }
}

async function executeAction(
  workspaceId: string,
  action: RuleAction,
  context: { contactId?: string; companyId?: string; [key: string]: unknown },
) {
  const params = action.params || {};

  switch (action.type) {
    case 'CREATE_TASK':
      await createTask({
        workspaceId,
        title: typeof params.title === 'string' ? params.title : 'Automated Rule Follow-up Task',
        description: typeof params.description === 'string' ? params.description : 'Generated by workspace automation rule',
        priority: (params.priority as TaskPriority) || 'HIGH',
        contactId: context.contactId,
        companyId: context.companyId,
        dueAt: new Date(Date.now() + 24 * 3600 * 1000),
      });
      break;

    case 'CREATE_TICKET':
      await createTicket({
        workspaceId,
        subject: typeof params.subject === 'string' ? params.subject : 'Automated Escalation Support Ticket',
        priority: (params.priority as TaskPriority) || 'HIGH',
        contactId: context.contactId,
        companyId: context.companyId,
      });
      break;

    case 'CREATE_DEAL':
      await createDeal({
        workspaceId,
        name: typeof params.name === 'string' ? params.name : 'Automated High Intent Opportunity',
        amount: typeof params.amount === 'number' ? params.amount : 12000,
        primaryContactId: context.contactId,
        primaryCompanyId: context.companyId,
      });
      break;

    case 'UPDATE_LIFECYCLE':
      if (context.contactId && typeof params.lifecycleStage === 'string') {
        await prisma.contact.update({
          where: { id: context.contactId },
          data: { lifecycleStage: params.lifecycleStage as LifecycleStage },
        });
      }
      break;
  }
}
